"""add fur color and gender to puppies

Revision ID: 267ecab477e2
Revises: eff51b35c510
Create Date: 2018-11-16 16:36:54.458836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '267ecab477e2'
down_revision = 'eff51b35c510'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('puppies', sa.Column('fur_color', sa.Text(), nullable=True))
    op.add_column('puppies', sa.Column('gender', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('puppies', 'gender')
    op.drop_column('puppies', 'fur_color')
    # ### end Alembic commands ###
